### ISSUE TITLE
Arisa doesn't try reconnecting and crashes if bugtracker is down

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#113]
**Describe the bug**
Arisa doesn't try reconnecting and crashes if bugtracker is down or the connection is refused

It should wait a minute and retry

**Comment by NeunEinser** [comment]
Since the merge of #112, arisa already shouldn't crash anymore.
Currently, it won't wait a minute, but wait the normal check interval, but that could be increased easily.

I don't know whether catching the exception and preventing the crash is already enough, though, or if the root cause is something like the session cookie being expired.

**Comment by urielsalis** [comment]
Even if we catch it we need to make sure we create a new jira client and try to reconnect that way

**Comment by NeunEinser** [comment]
I probably won't have time today, but might look into that tomorrow.
If someone else wants to have a go in the meantime, please do feel free to self-assign this issue and take a look yourselves.

**Comment by NeunEinser** [comment]
#112 seems to have prevented arisa from crashing, and also needing to restart it manually:
It might still be a good idea to try getting a new client, but this is not urgent anymore.
