### ISSUE TITLE
UpdateLinkedModule should include intervals for updating the linked count

### ISSUE THREAD

**Issue by Oval** [mojira/arisa-kt#131]
When a duplicate gets added, it'll update the linked count as soon as possible but this creates a rather "spamy" environment from Arisa; you don't really want couple of emails because a volunteer adds a lot of duplicates at once.

My suggestion would be to check whenever the linked counts get updated then wait for 30s, if another ticket gets added, wait for 1m (increase one linked = 30sec), ect. Would at least prevent most of the spam. **EDIT:** Example can be seen here: MCPE-69002

**Comment by violine1101** [comment]
I'd go a step further and would say that Linked should probably only be updated once per day on a ticket. That way that field could be updated in bulk. But I'm not sure if the current architecture supports this.

**Comment by urielsalis** [comment]
We could make a custom query that only updates the one for the day before

**Comment by NeunEinser** [comment]
Updating Linked once per day is not a good idea, because Arisa would need to go to a ton of tickets at once.
Always being 24h behind could work, I suppose, but that's not supported by the architecture currently.

Also I thought the update transition doesn't send emails anyways? Did that change in the update?

**Comment by violine1101** [comment]
It doesn't send emails, but it clutters both Arisa's profile activity feed, the general activity feed, and a ticket's history. So, it would make sense to "bundle" multiple new duplicates into a single action in order to reduce the amount of activity feed entries.

**Comment by Oval** [comment]
Pretty much what violine said above. I did not know it didn't send emails though.

**Comment by NeunEinser** [comment]
Honestly, I don't know if there is a really good solution to this.
Yes, we could look for issues that were updated pretty much 24h ago. However, tickets that get updated frequently would get lost.
Looking for a change that happened 24h ago would also not be what we want, as tickets that do get updated frequently would get checked by the module for every time it got updated, just 24h later.

**Comment by NeunEinser** [comment]
Okay, so I have thought about this a little more.

The module should see all issues that:
* Were updated recently, same as any other module
* Additionally see issues that were updated before currentTime -24h and before lastRun -24h.

Then the module itself could have a check that, for instance, asserts that the last change of the linked field is at least 24h ago. It might even make sense to go as far as to assert that the first added duplicates link after the last Linked update was 24h ago.
In case Linked has never been updated, issue creation should count.

This would make it so that the module would still see issues that are updated frequently. It might not update Linked exactly 24h later, but it will never be longer than 47h59m59s999ms (which would happen if the issue would receive an update 23:59:59.999 after the latest Linked change, the module would run at that time, and then the issue isn't updated and the module only sees it 24h later).
Personally, I like the idea of asserting the first added duplicates link after the last update of Linked should be 24h away, as it often happens that you are linking multiple issues in a batch and it would look kinda weird f the bot updates Linked and then right after that doesn't anymore.
