### ISSUE TITLE
Also consider issue summary and description for crash duplicates

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#169]
## The Problem
Currently, only attachments are checked for possible duplicates of a ticket. Perhaps it would make sense to extend this to ticket description and/or summary as well. Example: https://bugs.mojang.com/browse/MC-181380

## Possible Solutions
Either add a new module that also applies the logic from CrashModule to summary & description, or make the CrashModule check these fields as well.

**Comment by NeunEinser** [comment]
The description is already being checked for crash reports:
https://github.com/mojira/arisa-kt/blob/1b000539d52bf8268cd8a86af1dc83e9087cb587/src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt#L49

It didn't work there because it's not formatted like it should, likely visual mode is messing up the line breaks.
