### ISSUE TITLE
Automatically match duplicates by same reporter within short time period

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/arisa-kt#187]
## The Problem
Sometimes the same reporter will submit two tickets that are identical or nearly so. This may be due to the submission process, or it may be that the reporter is not paying attention or they get a web error, or use the back button or something.

## Possible Solution
Look back a few tickets to see if there is another from the same reporter. Compare the summary and description between the two and if it is a close (or even exact) match, resolve the second as a duplicate.

**Comment by Marcono1234** [comment]
Though in some cases user create a very similar report, e.g. when told that modded versions are not supported and then reproduce it in a vanilla version.
So maybe such a module should not run if the duplicated report is resolved.

**Comment by urielsalis** [comment]
Agree, we should leave this to the eyes of a human 😅

**Comment by Marcono1234** [comment]
I did not mean to completely reject this issue with my comment. The problem mentioned above could be solved by not having the module run if the original issue is already resolved. However, I assume that would cause some false negatives in case people duplicate their reports after they have been resolved e.g. because they are invalid.

Additionally it would be interesting to know if people actually create exact copies of their reports or change some information. I assume they change some parts of it, otherwise they would not have created a separate issue.

However, it would be useful if you could provide some example issues so we can have a closer look at them.
