### ISSUE TITLE
Unresolve reports closed for being in a different language if the reporter translates the ticket into English

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#343]
## The Problem
I've seen Arisa close issues for being in a different language, but then the reporter translates the ticket into English and it has to be put in the Discord requests in order for it to be opened again. (https://bugs.mojang.com/browse/MC-192463 is an example. Check the bug's history. It was originally in Spanish and resolved by Arisa, but then the reporter translated it into English and it took a while before it was reopened)
## Possible Solution
Arisa could detect changes to bugs with a specific comment (From Arisa) and check if the ticket is in English. If it is, Arisa could reopen it.

**Comment by urielsalis** [comment]
We discussed this when implementing the original language module. We only get 10k calls a day so calling for every update could get expensive, and in the message we tell users to open a new one instead of editing the old one(in this case a mod reopened manually as it was reported as a false positive until we saw the edit, but usually we leave them closed)
