### ISSUE TITLE
Forward log to a Discord channel

### ISSUE THREAD

**Issue by SPGoding** [mojira/arisa-kt#348]
## The Problem
Contributors besides the chosen ones can't enjoy the fancy ~~crash~~ logs 😭 
## Possible Solution
> but I think its easier for arisa to use a webhook url and just push
> -- urielsalis in [internal channel](https://discordapp.com/channels/647810384031645728/663488001346764805/727832773188124673)

**Comment by NeunEinser** [comment]
When should they be pushed?
The current log, and thus likely most interesting is always 'logs\\arisakt.html'
It seems like every day at around 07:00 UTC, a new log file is started. The old one then gets renamed to `arisakt-YYYY-MM-DD.0.txt`.
The current log always contains all entries going from 07:00 UTC.

We could of course everytime a new file that matches the above pattern is created, upload that file through the webhook (however that may work).
I think, however, that it would be more beneficial to do this more frequently so everyone can see issues that happened recently.

If that's possible, it would be the best solution, every time something is logged, push that line / these lines in text form to a webhook, so that we essentially have the entire log on Discord always.

**Comment by SPGoding** [comment]
Some interesting documentation: https://discord.com/developers/docs/resources/webhook

I might take a look at this later if no one else has the time ;D

**Comment by urielsalis** [comment]
I would pish at the same time we log the error

If there is an error, push it to the channel
