### ISSUE TITLE
Only reopen AR tickets if the requested piece of info is added

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#353]
## The Problem
When a crash report is asked for, and that ticket is resolved as AR, anyone can comment on the ticket and it will be reopened
## Possible Solution
Have Arisa look for comments by moderators/helpers that contain specific texts and then only reopen the ticket if that info is added and then delete the comment.
Arisa could look for the crash path in a mod's comment and then only reopen the ticket if a crash report is added
This could not be implemented for questions though.
Note: Arisa would not be resolving tickets as AR, but not reopening them if the info is not the correct info needed

**Comment by NeunEinser** [comment]
I guess a feasible way to actually only reopen on certain updates could be to add more tags like we already have `ARISA_KEEP_AR`, we could have something like `ARISA_REQUIRE_ATTACHMENT *.txt`.

**Comment by NeunEinser** [comment]
Although, that being said in case of a crash, a comment including the pasted crash report, or a pasted crash report that's being added to the description is of course also a valid reason to reopen a ticket that has been closed because of that.

**Comment by urielsalis** [comment]
So what do we want to do with this issue?

**Comment by violine1101** [comment]
I'm personally not really sure how this could be feasibly done. In most cases it would just be an additional burden on the moderator to explicitly specify for Arisa what it should do, if we use a command as proposed by @NeunEinser.

If we don't do a command, then Arisa would need to analyze the mod's comment, which I don't find viable.

Apart from that, I think this is still an issue that needs to be taken care of, it happens too often that Arisa reopens an AR ticket that has just been resolved by a mod because another user just commented by asking another question or similar.

**Comment by NeunEinser** [comment]
Might make sense to bring this up on Slack? I personally also don't think the command solution is necessarily the most optimal, it's just the only one I see to make this at least somewhat reliable.

For everything else I only see a pretty unreliable and pretty case-specific keyword search, or a general AI that can actually understand the question being asked, and possible responses to that (which is very obviously extremely far from viable)

**Comment by urielsalis** [comment]
Lets bring it, can you post it?

**Comment by Jack-McKalling** [comment]
Depending on how many of these tickets are pending at any one time, could it be viable to let arisa somehow keep track of a collection of these tickets, instead of trying to auto react on them? I really like the more specified variant of thing like "arisa require attachment" or "arisa require crash report" etc, as it would make arisa smarter in this task, but to actually detect a valid response to that is very difficult. Someone could attach a file, paste it in a comment, edit it into the description, or even add links to external files/logs. So a more specific command like that also requires a more intelligent reaction from the bot. However, if she doesn't need to react appropriately but only keep track of them, we could see a list of pending stuff and the changes made afterwards, and then we could simply judge ourselves. The downside of that is that it is a slower process and doesn't really notify anyone.

**Comment by urielsalis** [comment]
Closed after internal discussion
