### ISSUE TITLE
Remove new labels created by non-helpers/mods

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#381]
## The Problem
Users tend to create new labels that are not useful at all. Some random examples:
* https://bugs.mojang.com/browse/MC-118735
* https://bugs.mojang.com/browse/MC-138179
* https://bugs.mojang.com/browse/MC-153074
* https://bugs.mojang.com/browse/MC-156910
* https://bugs.mojang.com/browse/MC-157351
* https://bugs.mojang.com/browse/MC-160121
* https://bugs.mojang.com/browse/MC-186506
* https://bugs.mojang.com/issues/?jql=project+%3D+10400+AND+labels+%3D+HELP

I've made a dashboard that collects all labels on the MC project, if you want to take a look at it yourself. There's a lot of unnecessary stuff in there. It would be nice if labels could be actually useful. https://bugs.mojang.com/secure/Dashboard.jspa?selectPageId=19139

In the new guidelines draft, we have a rule that says "Don't add a label if it doesn't exist yet". Arisa could enforce this rule.

## Possible Solution
Arisa should remove a label from a ticket if there exists no other ticket created before `lastRun` with that label, unless that label has been added by a mod or helper. When a label is removed, Arisa does so silently without a warning in the comments, in order to prevent spam.

Before this is implemented, we should discuss whether this is really something that we need. If it is, we probably need to clean up the labels on the bug tracker too to make this feature actually useful.

**Comment by Tora-B** [comment]
I'm inclined to think that preemptively restricting users from creating new labels is somewhat self-defeating. They're presumably intended to be an organic categorization system, where multiple users independently apply the same label to related issues, but some moderation is necessary for them to be useful. Relying on a central authority to invent all necessary labels makes the system unresponsive, and we have alternative categorization systems that already function in that way. I think the organic property is beneficial, we just need an easy way to trim them.

I've attempted to clean up labels in the past, and it's a huge amount of neverending work, because you can't just wipe out a label, you have to go and remove it from every issue individually. It may be worth making a tool to manage an approved list of labels, from which unapproved labels could be either approved, or easily wiped from the tracker.

**Comment by NeunEinser** [comment]
> I've attempted to clean up labels in the past, and it's a huge amount of neverending work, because you can't just wipe out a label, you have to go and remove it from every issue individually.

You can remove labels using a bulk edit. If you have an appropriate search, for example by clicking one label, you can use bulk edit, select edit, go to labels and select "remove from existing" and then specify the label you want to remove. I just tested this successfully with "account". It does seem like different capitalizations are treated differently when doing a bulk remove, not by the filter though (as an issue with the label "Account" did remain at first).

Experienced users often do add new useful labels, though, as new bugs arise, "percision-loss", which was introduced by Connor, for example. The "approved" and "clean" set of labels are represented in the category, so completely blocking labels just because they are new doesn't seem like a good idea to me.
We could block unuseful labels that get added frequently, of course, if that seems worth it.

If labels are supposed to become more useful, removing labels that are not useful in general is not enough though. We'd need to remove unfitting labels and add missing labels too, and that does seem like a whole lot of work, we would need to do consistently, which I am not sure is worth the effort.

**Comment by Pokechu22** [comment]
What about adding a notice in a feed when a new label is created (and maybe also when all uses of one are deleted)?  That way they could be checked as they come along, without automatically removing them.  (And, when a label is newly created, it's only on one ticket, so it's easy to remove).

**Comment by violine1101** [comment]
After thinking about it for a bit, I've come to the conclusion that my approach above is not optimal in the way it determines what is a "new" label and what is not (since it would do a JIRA search every time, which in certain edge cases would produce an incorrect result).

Adding to that it might not always make sense to remove the ticket completely, and that there currently is no tech for a specific feed by Arisa as far as I'm aware (apart from simple `stdout` and `stderr` feeds to Discord), how about this:

Arisa would add a comment like `ARISA_NEW_LABEL <label_name>` every time it sees a new label being added. This way we can easily query tickets where a completely new label has been added recently. If Arisa notices that the label has been removed again, it would remove that comment (or we can edit it so that the ticket no longer shows up in the query).

That way we can still keep track of newly added labels, and remove them manually as needed, while still keeping potentially useful ones.

Another reason why I thought about this feature is that already existing labels are suggested when creating a new label, therefore bringing users to add more unhelpful labels the more unhelpful labels already exist. I find myself not using the label feature at all because it's so messy. As Torabi already mentioned, managing this whole thing is difficult, so I think it would be great if Arisa could help with that somehow.

**Comment by Jack-McKalling** [comment]
Firstly, if all existing labels are normalized, I think this will help a lot more in assisting users not adding unuseful labels. But besides that, I agree Arisa should in my opinion help with label management. If not completely blocking users from adding new ones, then in the form of keeping track for us what was newly added. I suggest that if this is done by letting her comment with some kind of magical keyword we can search for, to then restrict such comment to volunteers only. Because if a non-volunteer is not prevented from adding such a new label, they should also not be notified that they did.

I also think that preventing users from adding new labels altogether is not desirable. We should make our system for validating the label field more intelligent instead. Or at least more supportive for us like with above suggestions.

**Comment by urielsalis** [comment]
Closed after internal discussion
