### ISSUE TITLE
Prevent normal users from changing the displayed text of a link by having Arisa always revert the link's text back to the link's url

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#385]
## The Problem
As I stated in [WEB-2772](https://bugs.mojang.com/browse/WEB-2772), any user can link any text to any link. A user can pretend to be linking another ticket by editing the link text to an ticket number, when they actually are sending a malicious link or something similar.
## Possible Solution
Have Arisa revert any linked text to the url destination of the link from text created by a normal user. For example, when a user links to YouTube.com, but switches the text to say MC-12345, Arisa could change the text back to YouTube.com to show any user exactly where the link would be taking them.
I know this solution would stop Moderator and Helper links from looking the way they currently do, but I think that could be remedied by making so Arisa only reverts links from text created by non-mods and helpers, so the messages could stay the same.

**Comment by Marcono1234** [comment]
The problem you are mentioning is definitely a valid one but the proposed solution might be a little bit too destructive. E.g. if someone comments:
> This is an intended feature which is [described|...] in the changelog.

Replacing "described" with the URL would break the sentence. Additionally if the URL is rather long it might decrease readability.

What about having Arisa instead inserting in superscript the domain behind the link, e.g.:
> This is an intended feature which is [described|...]^minecraft.net^ in the changelog.

Though maybe there are ways in which an adversary is able to circumvent this as well.

**Comment by chandler05** [comment]
I'm not trying to solve the problem in WEB-2772, I'm just referring to it because there I explained how easy it was to make any link seem like a ticket ID/link

**Comment by Pokechu22** [comment]
Browsers show the link target when you hover over it, and barring sites that do stupid javascript changes after you click it (google...) this information can prevent issues like that.  For mobile browsers, you can't hover, but it should still show the link if you long-press it (not as great though).

I think restricting link titles in general is an overreaction, but perhaps it'd be reasonable to detect links of the form `[https://some-other-url|https://a-url]` and maybe `[https://some-other-url|MC-1234]` where there is an expectation as to the target.

**Comment by chandler05** [comment]
Actually, in Jira hovering over the link just says "Follow Link" instead of where it goes (At least in Chrome it does)

**Comment by Pokechu22** [comment]
That's the link's `title` attribute, but it should also show the URL at the bottom (at least, Firefox does, and I remember IE doing that; if chrome doesn't do it I'd be disappointed but not entirely surprised).  [Here's an image](https://user-images.githubusercontent.com/8334194/88491888-77606100-cf5b-11ea-9da7-4f75c64153ad.png).

**Comment by chandler05** [comment]
Chrome does do that, I just didn't notice it the first time

**Comment by Marcono1234** [comment]
> I think restricting link titles in general is an overreaction, but perhaps it'd be reasonable to detect links of the form `[https://some-other-url|https://a-url]` and maybe `[https://some-other-url|MC-1234]` where there is an expectation as to the target.

I don't think `[https://some-other-url|MC-1234]` is problematic, it is at most confusing when a ticket instead of a different website is opened. Similarly `[https://google.com|^Malicious attachment]` is likely not an issue either because due to the extension blocklist executables cannot be attached (or the user would have to perform additional steps to execute them once downloaded). Additionally Jira adds the green arrow indicating that the link points to an attachment.

For `[https://some-other-url|https://a-url]`, maybe trying to parse both text and link as URL and comparing the domains could work. Though there are certain things to consider:
- Should also detect URLs with IPv4 / IPv6 addresses as host
- Maybe there are edge cases where Java's `URL` or `URI` class parses a link differently than Jira or the browsers do

**Comment by Pokechu22** [comment]
Sorry, I forgot the link syntax; I meant `[MC-1234|https://some-other-url]`, i.e. looks like a link to a ticket, but it isn't.

**Comment by NeunEinser** [comment]
Comparing the main domain should be sufficient for the first case, e.g. `See the official post on [minecraft.net|https://www.minecraft.net/en-us/article/minecraft-snapshot-20w30a]` works, as both the subdomain (`www` in this case) and the path is ignored).

**Comment by Marcono1234** [comment]
> Comparing the main domain should be sufficient for the first case

Except for `.co.uk` (and similar) I guess? E.g.: `[trused.co.uk|malicious.co.uk]`

**Comment by NeunEinser** [comment]
I guess. Most of these are limited to certain uses though, (you can't create a domain with .gov.uk), so most of them are probably not too much of a concern.

**Comment by urielsalis** [comment]
We should match domain+subdomain+tld, as a lot of sites give you a subdomain to host things(like github) and that could be changed

**Comment by NeunEinser** [comment]
I feel like these cases should be filtered manually.
I think it's likely more harmful if because of a different subdomain the link text gets removed. Having a different subdomain for when you can host your own thing in a subdomain is not really different from a link text that does not look like a domain, but still suggests a different location than it actually leads to.

**Comment by Marcono1234** [comment]
But it is probably rather uncommon that the sub domains differ at the same level, e.g. you normally don't have something like:
> [bugs.mojang.com|status.mojang.com]

But rather something like the following where the link has an additional subdomain.
> [mojang.com|status.mojang.com]

So maybe only checking the domain parts which both text and link have could solve this. Though this would not detect the case where the subdomain can be user-controlled, e.g. `[example.com|http://user-controlled.example.com]`, but is this actually common?
Note however that for these cases the Java `URL` / `URI` parsing approach suggested by me above does not work because the protocol is missing.

**Comment by urielsalis** [comment]
Closed after internal discussion
