### ISSUE TITLE
Language Module: False positives with links?

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#419]
## The Bug
For some reason Arisa resolved the ticket below as Invalid for being in a different language, when all it the report was is a link
## Example Ticket
https://bugs.mojang.com/browse/WEB-2988

**Comment by Marcono1234** [comment]
Arisa actually sends <code><i>SUMMARY</i>. <i>DESCRIPTION</i>.</code> to the language detection API:
https://github.com/mojira/arisa-kt/blob/91c610529c959d10808caf4ed5745172a132bc73/src/main/kotlin/io/github/mojira/arisa/modules/LanguageModule.kt#L34-L42

And it appears that (for some reason) that API considers "Inappropriate username." as [100% Italian](https://dandelion.eu/semantic-text/entity-extraction-demo/?text=Inappropriate+username.&lang=auto&min_confidence=0.6&exec=true#results). On the other hand it looks like the URL does not contribute to the language detection at all, so the underlying issue is similar to #142 where the solution was to increase the text length threshold. Maybe Arisa should somehow detect and ignore URLs when calculating the text length.

**Comment by NeunEinser** [comment]
The most simple fix is probably to just use a regex to strip all urls from the final text
