### ISSUE TITLE
Language Module checking and removing comments

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#443]
## The Problem
Comments in another language are just as unhelpful as reports in a different language
## Possible Solution
Use the language module on comments and remove those in different languages

**Comment by urielsalis** [comment]
This might be really tricky, we are limited in the amount of calls we can make to the API (10k a day) and that might push it over the limit

**Comment by Marcono1234** [comment]
Having Arisa silently remove comments (or rather restrict their visibility) is not so nice especially if it is a false positive. It might even cause the author to add another comment because they think Mojira is not working correctly and their first comment got lost.
On the other hand having Arisa add a comment noting that the other non-English comment has been removed would create even more unnecessary noise, so that is likely not a solution to this either.

Do you have some specific comments in mind? I assume comments might in some cases be shorter than issue descriptions so the language recognition API could not even be used for them due to high false positive rates for short sentences, see #142.
