### ISSUE TITLE
Remove .pdf to the disallowed file extesions.

### ISSUE THREAD

**Issue by Chungui23** [mojira/arisa-kt#482]
.PDF are just images and they aren't supposed to be executable

**Comment by violine1101** [comment]
The reason for pdf files being removed is not because they are executable, but because they are documents. There's no reason to attach a document to a bug report, and if one has been attached it's usually a mistake.

**Comment by Pokechu22** [comment]
PDFs can contain JavaScript (see [this](https://www.codeproject.com/Articles/380293/Javascript-in-PDF)), and there was an issue where [arbitrary existing programs could be executed](https://web.archive.org/web/20100404034752/http://blogs.pcmag.com/securitywatch/2010/03/malicious_pdfs_execute_code_wi.php) (*probably* since fixed).  Though them being documents is the bigger issue (they aren't simple images).
