### ISSUE TITLE
Automatic updating linked field

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#51]
When marking a report as duplicate of another, either counting the number of duplicates on the parent and setting the pinned field, or incrementing the pinned field if counting isn't possible or is less efficient.

Moved from https://github.com/mojira/arisa-js/issues/5

**Comment by urielsalis** [comment]
Do we still need it?

**Comment by NeunEinser** [comment]
When I became helper, pinned and linked fields already weren't used anymore.

What were those fields intended for? Just a counter seems odd, as Jira already has that.

**Comment by urielsalis** [comment]
I agree. Closing

**Comment by NeunEinser** [comment]
Reopening for further discussion, see #57

**Comment by violine1101** [comment]
This would be a very useful statistic to see which tickets are frequently reported (i.e. if a recently reported ticket has a large number of duplicates, it's likely to be a severe issue). I don't think anything would be wrong with reviving the Pinned or Linked field (personally I'd prefer if the Linked field were to be used, as it's more appropriately named).

As far as I'm aware, the Pinned and Linked fields stopped being used before Arisa was developed because it was tedious to update them (it needed to be done manually as far as I know). This is also why this issue already existed in the original Arisa repository.

Of course this would need to be discussed with Mojang & the other mods as well though, but seeing as these fields are currently unused, I don't think anything speaks against giving them a purpose.

**Comment by Marcono1234** [comment]
`Linked` has been used differently in some cases where it contains the report ID instead of the count, see JQL: `Linked is not empty order by Linked DESC`
Though it appears this only affects a few older reports, however it would require clean up of them then.

We might also have to think about how trashed duplicates or update duplicated links (e.g. because the link was incorrect) should be handled, see for example MC-297 which currently only has 7 duplicates (but actually had multiple hundreds).

**Comment by violine1101** [comment]
I think it'd probably be most useful if it always contains the current number of duplicates, and that is probably also the easiest way to do it.
