### ISSUE TITLE
Arisa not detecting certain transaction IDs

### ISSUE THREAD

**Issue by Greymagic27** [mojira/arisa-kt#514]
## The Bug
Arisa should be detecting all transaction IDs and making the ticket private.

## Example Ticket
https://bugs.mojang.com/browse/MC-212366

## Expected behavior
To make the ticket private

**Comment by CubeTheThird** [comment]
Some of the patterns can be matched against fairly easily. Others are quite vague. Here would be example patterns:

Paypal:
[A-Z0-9]{17}
([A-Z0-9]{4}-){3}[A-Z0-9]{4}

Braintree:
[0-9]{6,7}   <- vague

Skrill:
[0-9]{9,10}   <- vague

DIBS:
[0-9]{9}   <- vague, also covered by Skrill pattern

Adyen:
[0-9]{16}   <- vague, though likely an ID since it's 16 digits

Gift Code:
([A-Z0-9]{5}-){5}[A-Z0-9]{5}
([A-Za-z0-9]{4}-){3}[A-Za-z0-9]{4}   <- partially matches paypal

Prepaid pin:
[0-9]{3} [0-9]{3} [0-9]{4}
([A-Z0-9]{5}-){5}[A-Z0-9]{5}   <- same as 1st gift code pattern

Order number:
[a-z0-9]{32}

**Comment by SPGoding** [comment]
Are transaction IDs always prepended with the transaction method? If so, we could potentially match with `braintree:[A-Z0-9]+` :eyes:

**Comment by CubeTheThird** [comment]
They may be, however it is up to the reporter whether they include that part. Would make it easier to determine if it's genuinely an ID or a false positive though.

**Comment by urielsalis** [comment]
For braintree they are, for the others no

**Comment by urielsalis** [comment]
Final regexes:

Paypal:
[A-Z0-9]{17}
([A-Z0-9]{4}-){3}[A-Z0-9]{4}

Braintree:
braintree:[0-9]{6,7}

Gift Code:
([A-Z0-9]{5}-){5}[A-Z0-9]{5}
([A-Za-z0-9]{4}-){3}[A-Za-z0-9]{4} <- partially matches paypal

Prepaid pin:
[0-9]{3} [0-9]{3} [0-9]{4}

Order number:
[a-z0-9]{32}
