### ISSUE TITLE
Make issues private if they contain certain words

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/arisa-kt#598]
## The Problem
Spammers create tickets about "herobrine", etc. This encourages other copycat spammers to do the same. Could also look for vulgarity, including in new comments and make those restricted also.

## Possible Solution
Have a list of keywords that, if present, will cause Arisa to make an issue private, and possibly add the "keep private" setting too.

**Comment by SPGoding** [comment]
There is already [such a module](https://github.com/mojira/arisa-kt/blob/f871faae39471beb916f66368f5a50cf5598be2c/src/main/kotlin/io/github/mojira/arisa/modules/PrivacyModule.kt#L14) that checks the summary, description, environment, attachments, and comments. It doesn't do the "keep private" thing though, but it should be easy to add it as a boolean option to the `patterns` variable.

**Comment by Jack-McKalling** [comment]
They might as well be able to see all triggers from here and find loopholes or simply new words that aren't covered yet.

**Comment by Marcono1234** [comment]
Maybe for the Herobrine case it would be best to just resolve as "Incomplete", since that helper message also links to the guidelines.
I am not sure if making them private adds much value (except maybe preventing copycat spammers as you mentioned).
What do you think?

There are indeed multiple reports from the past few months about Herobrine (some of them trashed). What other (non-vulgar) words are you thinking of?

**Comment by MikeUnverferth** [comment]
I'm fine with leaving it the way it is, especially since the code is currently public anyway.
