### ISSUE TITLE
README logo and description are no longer centered

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#653]
## The Bug
The logo and the description in the README are no longer centered, but instead are left-aligned:
![README screenshot](https://user-images.githubusercontent.com/11685886/118405011-bd66ec80-b675-11eb-8047-d0cad2ca0c9a.png)

Apparently GitHub is removing the `style` attribute from the HTML code.
As temporary alternative we could use the deprecated `align="center"` attribute, though we should probably look for alternatives.

**Comment by Pokechu22** [comment]
GitHub allows [these](https://github.com/gjtorikian/html-pipeline/blob/0e3d84eb13845e0d2521ef0dc13c9c51b88e5087/lib/html/pipeline/sanitization_filter.rb#L51-L77) attributes ([this used to be specified in the readme, but isn't anymore](https://github.com/github/markup/commit/56a58500418779ee3e06db2bfcd86654acbf2ce7)).  `style` is not included, but `align` is; arbitrary CSS can actually lead to arbitrary code execution in some browsers due to silly design choices.

`align` is probably the right choice.
