### ISSUE TITLE
Arisa incorrectly closes bug reports if level was modded

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#764]
## The Bug
Arisa closes bug reports as invalid if the world was opened with a mod, it shouldn't do that.

## Example Ticket
https://bugs.mojang.com/browse/MC-250632

## Expected behavior
Maybe only leave a comment like "Note: World save file has been opened with a mod" but not close the bug report

**Comment by Pokechu22** [comment]
Are we sure that that's actually the cause, and not e.g. the report being directly posted in the body of the ticket instead of as an attachment?  (Both of these conditions apply to both that ticket and https://bugs.mojang.com/browse/MC-250657, where this also happened.)  Arisa doesn't seem to check the was-modded status of the report as far as I can tell.

**Comment by SPGoding** [comment]
I don't think Arisa checks `Level was modded: true` at all. The `Crash.Minecraft` class provided by the `mc-crash-lib` [has `modded` and `wasLevelModded` fields separately](https://github.com/urielsalis/mc-crash-lib/blob/a00d4c763d4ca8d0dde5b11ba6f11475fbf2e0ff/src/main/kotlin/com/urielsalis/mccrashlib/Crash.kt#L7-L15), and Arisa [only checks the `modded` field](https://github.com/mojira/arisa-kt/blob/73948eb9f58a2f41d1b926b7fcedd4de84f53074/src/main/kotlin/io/github/mojira/arisa/modules/CrashModule.kt#L117) as far as i know.

**Comment by SPGoding** [comment]
Could it be caused by the `N` in `Probably Not` [here](https://github.com/urielsalis/mc-crash-lib/blob/a00d4c763d4ca8d0dde5b11ba6f11475fbf2e0ff/src/main/kotlin/com/urielsalis/mccrashlib/parser/MinecraftCrashParser.kt#L75) being capitalized, while the report in the ticket has it in lowercase?

**Comment by Pokechu22** [comment]
I believe the `true` parameter there indicates a case-insensitive check (based on [this documentation](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/contains.html)).

**Comment by Marcono1234** [comment]
Relates to https://github.com/urielsalis/mc-crash-lib/pull/21 and https://github.com/mojira/helper-messages/pull/178

Sorry for not following up on this; it appears the problem here is that Arisa is still using mc-crash-lib 2.0.5, but those changes separating the two modded states are only on the `master` branch and have not been released yet.
